src/SportCommunityRM.WebSite/ViewModels/Team/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SportCommunityRM.WebSite.ViewModels.Team
{
    public class CreateViewModel
    {
        [Display(Name = "Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Min. Birth Year")]
        [Range(ushort.MinValue, ushort.MaxValue, ErrorMessage = "Insert a valid year")]
        public int? MinBirthYear { get; set; }

        [Display(Name = "Max. Birth Year")]
        [Range(ushort.MinValue, ushort.MaxValue, ErrorMessage = "Insert a valid year")]
        public int? MaxBirthYear { get; set; }

        [Display(Name = "Players")]
        public Player[] Players { get; set; }

        [Display(Name = "Coaches")]
        public Coach[] Coaches { get; set; }

        public class Player
        {
            public Guid Id { get; set; }

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string Name => $"{FirstName} {LastName}";

            public string FullInfo => $"{Name} ({BirthDate.ToShortDateString()})";

            public DateTime BirthDate { get; set; }

            public bool IsCaptain { get; set; }
        }

        public class Coach
        {
            public Guid Id { get; set; }

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string Name => $"{FirstName} {LastName}";

            public string FullInfo => $"{Name} ({BirthDate.ToShortDateString()})";

            public DateTime BirthDate { get; set; }

            public bool IsMainCoach { get; set; }
        }
    }
}

src/SportCommunityRM.WebSite/ViewModels/Team/DetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SportCommunityRM.WebSite.ViewModels.Team
{
    public class DetailViewModel : IPermissionsViewModel
    {
        public DetailViewModel() : base(isCreateAllowed: false, isDeleteAllowed: false, isEditAllowed: false) { }

        public DetailViewModel(bool isCreateAllowed, bool isDeleteAllowed, bool isEditAllowed) 
            : base(isCreateAllowed, isDeleteAllowed, isEditAllowed)
        {
        }

        public Guid Id { get; set; }

        public string PictureId { get; set; }

        public string BackgroundPictureId { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Min. Birth Year")]
        public int? MinBirthYear { get; set; }

        [Display(Name = "Max. Birth Year")]
        public int? MaxBirthYear { get; set; }

        public IEnumerable<Player> Players { get; set; }

        public IEnumerable<Coach> Coaches { get; set; }

        public Activity[] Activities { get; set; }

        public class Player
        {
            public Guid Id { get; set; }

            public string Name { get; set; }

            public DateTime BirthDate { get; set; }
        }

        public class Coach
        {
            public Guid Id { get; set; }

            public string Name { get; set; }
        }

        public class Activity
        {
            public Guid Id { get; set; }

            public string Name { get; set; }

            public ActivityType ActivityType { get; set; }
        }

        public enum ActivityType
        {
            Match,
            Tournament,
            Training
        }
    }
}

src/SportCommunityRM.WebSite/ViewModels/Team/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SportCommunityRM.WebSite.ViewModels.Team
{
    public class EditViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "Name")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Min. Birth Year")]
        [Range(ushort.MinValue, ushort.MaxValue, ErrorMessage = "Insert a valid year")]
        public int? MinBirthYear { get; set; }

        [Display(Name = "Max. Birth Year")]
        [Range(ushort.MinValue, ushort.MaxValue, ErrorMessage = "Insert a valid year")]
        public int? MaxBirthYear { get; set; }

        [Display(Name = "Players")]
        public Player[] Players { get; set; }

        [Display(Name = "Coaches")]
        public Coach[] Coaches { get; set; }

        public class Player
        {
            public Guid Id { get; set; }

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string Name => $"{FirstName} {LastName}";

            public string FullInfo => $"{Name} ({BirthDate.ToShortDateString()})";

            public DateTime BirthDate { get; set; }

            public bool IsCaptain { get; set; }
        }

        public class Coach
        {
            public Guid Id { get; set; }

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public string Name => $"{FirstName} {LastName}";

            public string FullInfo => $"{Name} ({BirthDate.ToShortDateString()})";

            public DateTime BirthDate { get; set; }

            public bool IsMainCoach { get; set; }
        }
    }
}

src/SportCommunityRM.WebSite/ViewModels/Team/IndexViewModel.cs
using System;
using System.Collections.Generic;

namespace SportCommunityRM.WebSite.ViewModels.Team
{
    public class IndexViewModel : IPermissionsViewModel
    {
        public IndexViewModel(bool isCreateAllowed, bool isDeleteAllowed, bool isEditAllowed) 
            : base(isCreateAllowed, isDeleteAllowed, isEditAllowed)
        {
        }

        public IEnumerable<Team> Teams { get; set; }

        public class Team
        {
            public Guid Id { get; set; }

            public string Name { get; set; }

            public int PlayersCount { get; set; }

            public int CoachesCount { get; set; }
        }
    }
}

src/SportCommunityRM.WebSite/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.WebSite.Models;
using SportCommunityRM.WebSite.WorkerServices;
using SportCommunityRM.WebSite.ViewModels.Coach;
using Microsoft.AspNetCore.Authorization;

namespace SportCommunityRM.WebSite.Controllers
{
    [Authorize]
    public class CoachController : BaseController, IUserSearchController
    {
        private readonly CoachControllerWorkerServices WorkerServices;

        public CoachController(CoachControllerWorkerServices workerServices)
        {
            this.WorkerServices = workerServices ?? throw new ArgumentNullException(nameof(workerServices));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await this.WorkerServices.GetIndexViewModelAsync();

            return View(model);
        }

        [HttpPost]
        public IEnumerable<UserSearchResult> SearchUser([FromBody] UserSearchRequest request)
        {
            var results = this.WorkerServices.SearchUser(request.Filter);

            return results;
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateCoaches))]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateCoaches))]
        public async Task<IActionResult> Add(AddViewModel viewModel)
        {
            if (!ModelState.IsValid || viewModel.Id.IsNullOrEmpty())
                return View(viewModel);

            await this.WorkerServices.CreateCoachIfNotExists(viewModel.Id.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteTeams))]
        public async Task<IActionResult> Remove(Guid? coachId, Guid? teamId)
        {
            if (coachId.IsNullOrEmpty() || teamId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemoveCoachFromTeamAsync(coachId.Value, teamId.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteCoaches))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.DeleteCoachAsync(id.Value);

            return RedirectToAction(nameof(this.Index));
        }
    }
}

src/SportCommunityRM.WebSite/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.WebSite.WorkerServices;
using SportCommunityRM.WebSite.ViewModels.Team;
using SportCommunityRM.WebSite.Models;
using Microsoft.AspNetCore.Authorization;
using SportCommunityRM.WebSite.Helpers;

namespace SportCommunityRM.WebSite.Controllers
{
    [Authorize]
    public class TeamController : BaseController, IUserSearchController, IPictureController
    {
        private readonly TeamControllerWorkerServices WorkerServices;

        public TeamController(TeamControllerWorkerServices workerServices)
        {
            this.WorkerServices = workerServices ?? throw new ArgumentNullException(nameof(workerServices));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await this.WorkerServices.GetIndexViewModelAsync();

            return View(model);
        }

        [HttpPost]
        public IEnumerable<UserSearchResult> SearchUser([FromBody] UserSearchRequest request)
        {
            if (request == null)
                return new UserSearchResult[0];

            var results = this.WorkerServices.SearchUser(request.Filter, request.MinBirthYear, request.MaxBirthYear, request.IdsToExclude);

            return results;
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateTeams))]
        public IActionResult Create()
        {
            var model = this.WorkerServices.GetCreateViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateTeams))]
        public async Task<IActionResult> Create(CreateViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            await this.WorkerServices.CreateTeamAsync(viewModel);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public IActionResult Edit(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            var model = this.WorkerServices.GetEditViewModel(id.Value);

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> Edit(EditViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            await this.WorkerServices.EditTeamAsync(viewModel);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteTeams))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.DeleteTeamAsync(id.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            var model = this.WorkerServices.GetDetailViewModel(id.Value);

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> RemoveCoach(Guid? teamId, Guid? coachId)
        {
            if (teamId.IsNullOrEmpty() || coachId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemoveCoachAsync(teamId.Value, coachId.Value);

            return RedirectToAction(nameof(this.Detail), new { id = teamId.Value });
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> RemovePlayer(Guid? teamId, Guid? playerId)
        {
            if (teamId.IsNullOrEmpty() || playerId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemovePlayerAsync(teamId.Value, playerId.Value);

            return RedirectToAction(nameof(this.Detail), new { id = teamId.Value });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Picture(Guid teamId, int? size)
        {
            var bytes = await this.WorkerServices.GetTeamPictureAsync(teamId, size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetPicture(string pictureId, int? size)
        {
            var bytes = await this.WorkerServices.GetPictureAsync(pictureId, "/images/default.jpg", size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }
    }
}

src/SportCommunityRM.WebSite/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.WebSite.Helpers;
using SportCommunityRM.WebSite.Models;
using SportCommunityRM.WebSite.WorkerServices;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SportCommunityRM.WebSite.Controllers
{
    [Authorize]
    public class UserController : BaseController, IActivityController, INewsFeedController, IPictureController
    {
        private readonly UserControllerWorkerServices WorkerServices;

        public UserController(UserControllerWorkerServices workerServices)
        {
            this.WorkerServices = workerServices ?? throw new ArgumentNullException(nameof(workerServices));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await this.WorkerServices.GetIndexViewModelAsync();

            return View(model);
        }

        public async Task<IActionResult> GetActivitiesAsync(string filter, int page, string sortExpression)
        {
            var userId = this.User.GetUserId();

            var activities = await this.WorkerServices.GetActivitiesAsync(userId, filter, page: page, sortExpression: sortExpression);

            return PartialView("DisplayTemplates/Activities", activities);
        }

        [HttpPost]
        public async Task<CalendarEvent[]> GetCalendarEventsAsync([FromBody] CalendarEventsRequest request)
        {
            var userId = this.User.GetUserId();

            var newsFeedContents = await this.WorkerServices.GetUserCalendarEventsAsync(
                userId,
                request.Overlap,
                request.Editable,
                request.DurationEditable,
                request.StartDate,
                request.EndDate);

            return newsFeedContents;
        }

        public async Task<IActionResult> GetFeedAsync(int page)
        {
            var userId = this.User.GetUserId();

            var newsFeedContents = await this.WorkerServices.GetFeedAsync(userId, page: page);

            return PartialView("DisplayTemplates/NewsFeed", newsFeedContents);
        }
        
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(Guid id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            var model = this.WorkerServices.GetDetailViewModel(id);

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> UserPicture(string username, int? size)
        {
            var bytes = await this.WorkerServices.GetUserPictureByUsernameAsync(username, size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }

        public async Task<IActionResult> UserIdPicture(Guid id, int? size)
        {
            var bytes = await this.WorkerServices.GetUserPictureByIdAsync(id, size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetPicture(string pictureId, int? size)
        {
            var defaultStaticImagePath = this.WorkerServices.GetDefaultStaticImagePath();

            var bytes = await this.WorkerServices.GetPictureAsync(pictureId, defaultStaticImagePath, size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }
    }
}

src/SportCommunityRM.WebSite/Views/Team/Detail.cshtml
@model SportCommunityRM.WebSite.ViewModels.Team.DetailViewModel
@{
    ViewData["Title"] = $"Team '{Model.Name}'";
    var pictureUrl = Url.Action(nameof(IPictureController.GetPicture), new { pictureId = Model.PictureId });
    var backgroundPictureUrl = Url.Action(nameof(IPictureController.GetPicture), new { pictureId = Model.BackgroundPictureId });
}

@section ParallaxBgStyleSection{
    <style type="text/css">
        .parallax-html .parallax-header::before {
            background: linear-gradient(to bottom, transparent, #0081cc 90%), url('/images/team_test.jpg') center no-repeat;
        }
    </style>
}

@section HeaderSection{
    <div class="col-md-8">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="col-md-4 hidden-xs">
        <img src="/images/team_test.jpg" class="img-responsive parallax-title-picture" />
        @*<img src="@pictureUrl" class="pull-right img-responsive parallax-title-picture" />*@
    </div>
}

<div class="col-md-6">
    <div class="panel panel-accent">
        <div class="panel-heading" role="tab" id="players-heading">
            <div class="inline-children">
                <a href="#players-collapse" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="players-collapse">
                    <h4 class="panel-title">
                        <i class="fa fa-group"></i> Players
                    </h4>
                </a>
                <a href="#players-collapse" class="collapse-btn bold pull-right" role="button" data-toggle="collapse" title="Toggle" aria-expanded="true" aria-controls="players-collapse">
                    <i class="glyphicon glyphicon-menu-up"></i>
                </a>
            </div>
        </div>
        <div class="panel-collapse collapse in" role="tabpanel" id="players-collapse" aria-labelledby="players-heading">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Birth date</th>
                                <th>@*Actions header*@</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Players.IsNullOrEmpty())
                            {
                                <tr>
                                    <td colspan="3">No player to display</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var player in Model.Players)
                                {
                                    <tr>
                                        <td>@player.Name</td>
                                        <td>@player.BirthDate.ToShortDateString()</td>
                                        <td>
                                            <a class="text-accent" asp-action="Detail" asp-controller="User" asp-route-id="@player.Id" title="Detail">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </a>
                                            @if (Model.IsDeleteAllowed)
                                            {
                                                <a data-remove-player-btn class="text-danger" asp-action="@nameof(TeamController.RemovePlayer)" asp-controller="Team" asp-route-playerId="@player.Id" asp-route-teamId="@Model.Id" title="Remove player">
                                                    <i class="glyphicon glyphicon-remove"></i>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="panel panel-accent">
        <div class="panel-heading" role="tab" id="coaches-heading">
            <div class="inline-children">
                <a href="#coaches-collapse" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="coaches-collapse">
                    <h4 class="panel-title">
                        <i class="fa fa-user"></i> Coaches
                    </h4>
                </a>
                <a href="#coaches-collapse" class="collapse-btn bold pull-right" role="button" data-toggle="collapse" title="Toggle" aria-expanded="true" aria-controls="coaches-collapse">
                    <i class="glyphicon glyphicon-menu-up"></i>
                </a>
            </div>
        </div>
        <div class="panel-collapse collapse in" role="tabpanel" id="coaches-collapse" aria-labelledby="coaches-heading">
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>@*Actions header*@</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Coaches.IsNullOrEmpty())
                            {
                                <tr>
                                    <td colspan="2">No coach to display</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var coach in Model.Coaches)
                                {
                                    <tr>
                                        <td>@coach.Name</td>
                                        <td>
                                            <a class="text-accent" asp-action="Detail" asp-controller="Coach" asp-route-id="@coach.Id" title="Detail">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </a>
                                            @if (Model.IsDeleteAllowed)
                                            {
                                                <a data-remove-coach-btn class="text-danger" asp-action="@nameof(TeamController.RemoveCoach)" asp-controller="Team" asp-route-playerId="@coach.Id" asp-route-teamId="@Model.Id" title="Remove coach">
                                                    <i class="glyphicon glyphicon-remove"></i>
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
    <button type="button" class="btn btn-block-fluid btn-danger" onclick="history.back()">Back</button>
</div>

@if (Model.IsDeleteAllowed)
{
    <script type="text/javascript">
        $(function () {
            $('[data-remove-player-btn]').on('click', function (event) {
                event.preventDefault();
                var removeUrl = $(this).attr('href');
                showConfirm('Are you sure to remove this player from @Model.Name?', 'Yes', 'No', function (result) {
                    if (result) window.location.href = removeUrl;
                });
            });
            $('[data-remove-coach-btn]').on('click', function (event) {
                event.preventDefault();
                var removeUrl = $(this).attr('href');
                showConfirm('Are you sure to remove this coach from @Model.Name?', 'Yes', 'No', function (result) {
                    if (result) window.location.href = removeUrl;
                });
            });
        });
    </script>
}

src/SportCommunityRM.WebSite/Views/Team/Index.cshtml
@model SportCommunityRM.WebSite.ViewModels.Team.IndexViewModel
@{
    ViewData["Title"] = "Teams";
}

@section ParallaxBgStyleSection{
    <style type="text/css">
        .parallax-html .parallax-header::before {
            background: linear-gradient(to bottom, transparent, #0081cc 90%), url('/images/team_test.jpg') center no-repeat;
        }
    </style>
}

@section HeaderSection{
    <h2>@ViewData["Title"]</h2>
}

<div class="col-md-12">
    <div class="panel panel-accent">
        <div class="panel-heading" role="tab" id="teams-heading">
            <div class="inline-children">
                <a href="#teams-collapse" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="teams-collapse">
                    <h4 class="panel-title">
                        <i class="fa fa-group"></i> @ViewData["Title"]
                    </h4>
                </a>
                <a href="#teams-collapse" class="collapse-btn bold pull-right" role="button" data-toggle="collapse" title="Toggle" aria-expanded="true" aria-controls="teams-collapse">
                    <i class="glyphicon glyphicon-menu-up"></i>
                </a>
            </div>
        </div>
        <div class="panel-collapse collapse in" role="tabpanel" id="teams-collapse" aria-labelledby="teams-heading">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Players count</th>
                                        <th>Coaches count</th>
                                        <th>@*Actions header*@</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Teams == null || !Model.Teams.Any())
                                    {
                                        <tr>
                                            <td colspan="4">No team to display</td>
                                        </tr>
                                    }
                                    else
                                    {
                                        foreach (var team in Model.Teams)
                                        {
                                            <tr>
                                                <td>@team.Name</td>
                                                <td>@team.PlayersCount</td>
                                                <td>@team.CoachesCount</td>
                                                <td>
                                                    <a class="text-accent" title="Detail" asp-action="Detail" asp-controller="Team" asp-route-id="@team.Id">
                                                        <i class="glyphicon glyphicon-search"></i>
                                                    </a>
                                                    @if (Model.IsEditAllowed)
                                                    {
                                                        <a data-edit-team-btn class="text-primary" title="Edit" asp-action="Edit" asp-controller="Team" asp-route-id="@team.Id">
                                                            <i class="glyphicon glyphicon-edit"></i>
                                                        </a>
                                                    }
                                                    @if (Model.IsDeleteAllowed)
                                                    {
                                                        <a data-delete-team-btn class="text-danger" title="Delete" asp-action="Delete" asp-controller="Team" asp-route-id="@team.Id">
                                                            <i class="glyphicon glyphicon-remove"></i>
                                                        </a>
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                @if (Model.IsCreateAllowed)
                {
                    <br />
                    <div class="row">
                        <div class="col-md-12">
                            <a class="btn btn-success pull-right" title="Create new team" asp-action="Create" asp-controller="Team">
                                Create new team <i class="glyphicon glyphicon-plus"></i>
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@if (Model.IsDeleteAllowed)
{
    <script type="text/javascript">
        $(function () {
            $('[data-delete-team-btn]').on('click', function (event) {
                event.preventDefault();
                var deleteUrl = $(this).attr('href');
                showConfirm('Are you sure to delete this team? All players and coaches will be removed from the deleted team.', 'Yes', 'No', function (result) {
                    if (result) window.location.href = deleteUrl;
                });
            });
        });
    </script>
}