src/SportCommunityRM.WebSite/ViewModels/Shared/ActivitiesViewModel.cs
using ReflectionIT.Mvc.Paging;
using System;
using System.ComponentModel.DataAnnotations;

namespace SportCommunityRM.WebSite.ViewModels.Shared
{
    public class ActivitiesViewModel
    {
        [UIHint(nameof(Activities))]
        public PagingList<Activity> Activities { get; set; }

        public class Activity
        {
            public Guid Id { get; set; }

            [Display(Name = "Name")]
            public string Name { get; set; }

            [Display(Name = "Start date")]
            public DateTime StartDate { get; set; }

            [Display(Name = "End date")]
            public DateTime EndDate { get; set; }
        }
    }
}

src/SportCommunityRM.WebSite/ViewModels/Shared/CalendarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportCommunityRM.WebSite.ViewModels.Shared
{
    public class CalendarViewModel : UniqueViewModel
    {
        public string DataUrl { get; set; }

        public bool Overlap { get; set; }

        public bool Editable { get; set; }

        public bool Selectable { get; set; }

        public bool DurationEditable { get; set; }
    }
}

src/SportCommunityRM.WebSite/ViewModels/Shared/ErrorViewModel.cs
using System;

namespace SportCommunityRM.WebSite.ViewModels.Shared
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/SportCommunityRM.WebSite/ViewModels/Shared/NewsFeedViewModel.cs
using ReflectionIT.Mvc.Paging;
using System;
using System.ComponentModel.DataAnnotations;

namespace SportCommunityRM.WebSite.ViewModels.Shared
{
    public class NewsFeedViewModel
    {
        [UIHint(nameof(NewsFeed))]
        public PagingList<Content> NewsFeed { get; set; }

        public class Content
        {
            public Guid Id { get; set; }

            public string Title { get; set; }

            public string Caption { get; set; }

            public string Thumbnail { get; set; }

            public DateTime PublicationDate { get; set; }

            public ContentType Type { get; set; }
        }

        public enum ContentType
        {
            Article = 0,
            MatchReport = 1
        }
    }
}

src/SportCommunityRM.WebSite/Components/LoginViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.Data.Models;
using SportCommunityRM.Data.ReadModel;
using SportCommunityRM.WebSite.Models;
using System;
using System.Security.Claims;

namespace SportCommunityRM.WebSite.Components
{
    public class LoginViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> UserManager;
        private readonly SignInManager<ApplicationUser> SignInManager;
        private readonly IDatabase Database;

        public LoginViewComponent(
            UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signInManager,
            IDatabase database)
        {
            this.UserManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            this.SignInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
            this.Database = database ?? throw new ArgumentNullException(nameof(database));
        }

        public IViewComponentResult Invoke()
        {
            var userId = this.UserClaimsPrincipal.GetUserId();

            var registeredUser = this.Database.RegisteredUsers.WithUserId(userId);
            if (registeredUser == null)
                return View(new Model());

            var username = UserManager.GetUserName(this.UserClaimsPrincipal);

            var isLogged = SignInManager.IsSignedIn(this.UserClaimsPrincipal);

            var model = new Model
            {
                RegisteredUserId = registeredUser.Id,
                Username = username,
                FirstName = registeredUser.FirstName,
                LastName = registeredUser.LastName,
                IsLogged = isLogged
            };

            return View(model);
        }

        public class Model
        {
            public Guid RegisteredUserId { get; set; }

            public string Username { get; set; }

            public string FirstName { get; set; }

            public string LastName { get; set; }

            public bool IsLogged { get; set; }

            public string[] Roles { get; set; }
        }
    }
}

src/SportCommunityRM.WebSite/Controllers/CoachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.WebSite.Models;
using SportCommunityRM.WebSite.WorkerServices;
using SportCommunityRM.WebSite.ViewModels.Coach;
using Microsoft.AspNetCore.Authorization;

namespace SportCommunityRM.WebSite.Controllers
{
    [Authorize]
    public class CoachController : BaseController, IUserSearchController
    {
        private readonly CoachControllerWorkerServices WorkerServices;

        public CoachController(CoachControllerWorkerServices workerServices)
        {
            this.WorkerServices = workerServices ?? throw new ArgumentNullException(nameof(workerServices));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await this.WorkerServices.GetIndexViewModelAsync();

            return View(model);
        }

        [HttpPost]
        public IEnumerable<UserSearchResult> SearchUser([FromBody] UserSearchRequest request)
        {
            var results = this.WorkerServices.SearchUser(request.Filter);

            return results;
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateCoaches))]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateCoaches))]
        public async Task<IActionResult> Add(AddViewModel viewModel)
        {
            if (!ModelState.IsValid || viewModel.Id.IsNullOrEmpty())
                return View(viewModel);

            await this.WorkerServices.CreateCoachIfNotExists(viewModel.Id.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteTeams))]
        public async Task<IActionResult> Remove(Guid? coachId, Guid? teamId)
        {
            if (coachId.IsNullOrEmpty() || teamId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemoveCoachFromTeamAsync(coachId.Value, teamId.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteCoaches))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.DeleteCoachAsync(id.Value);

            return RedirectToAction(nameof(this.Index));
        }
    }
}

src/SportCommunityRM.WebSite/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportCommunityRM.WebSite.WorkerServices;
using SportCommunityRM.WebSite.ViewModels.Team;
using SportCommunityRM.WebSite.Models;
using Microsoft.AspNetCore.Authorization;
using SportCommunityRM.WebSite.Helpers;

namespace SportCommunityRM.WebSite.Controllers
{
    [Authorize]
    public class TeamController : BaseController, IUserSearchController, IPictureController
    {
        private readonly TeamControllerWorkerServices WorkerServices;

        public TeamController(TeamControllerWorkerServices workerServices)
        {
            this.WorkerServices = workerServices ?? throw new ArgumentNullException(nameof(workerServices));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await this.WorkerServices.GetIndexViewModelAsync();

            return View(model);
        }

        [HttpPost]
        public IEnumerable<UserSearchResult> SearchUser([FromBody] UserSearchRequest request)
        {
            if (request == null)
                return new UserSearchResult[0];

            var results = this.WorkerServices.SearchUser(request.Filter, request.MinBirthYear, request.MaxBirthYear, request.IdsToExclude);

            return results;
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateTeams))]
        public IActionResult Create()
        {
            var model = this.WorkerServices.GetCreateViewModel();

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.CreateTeams))]
        public async Task<IActionResult> Create(CreateViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            await this.WorkerServices.CreateTeamAsync(viewModel);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public IActionResult Edit(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            var model = this.WorkerServices.GetEditViewModel(id.Value);

            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> Edit(EditViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            await this.WorkerServices.EditTeamAsync(viewModel);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.DeleteTeams))]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.DeleteTeamAsync(id.Value);

            return RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(Guid? id)
        {
            if (id.IsNullOrEmpty())
                return NotFound();

            var model = this.WorkerServices.GetDetailViewModel(id.Value);

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> RemoveCoach(Guid? teamId, Guid? coachId)
        {
            if (teamId.IsNullOrEmpty() || coachId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemoveCoachAsync(teamId.Value, coachId.Value);

            return RedirectToAction(nameof(this.Detail), new { id = teamId.Value });
        }

        [HttpGet]
        [Authorize(Policy = nameof(ClaimPoliciesConstants.EditTeams))]
        public async Task<IActionResult> RemovePlayer(Guid? teamId, Guid? playerId)
        {
            if (teamId.IsNullOrEmpty() || playerId.IsNullOrEmpty())
                return NotFound();

            await this.WorkerServices.RemovePlayerAsync(teamId.Value, playerId.Value);

            return RedirectToAction(nameof(this.Detail), new { id = teamId.Value });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Picture(Guid teamId, int? size)
        {
            var bytes = await this.WorkerServices.GetTeamPictureAsync(teamId, size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetPicture(string pictureId, int? size)
        {
            var bytes = await this.WorkerServices.GetPictureAsync(pictureId, "/images/default.jpg", size);

            return File(bytes ?? new byte[0], ImagesHelper.JpegMimeType);
        }
    }
}

src/SportCommunityRM.WebSite/Views/Shared/_ActivitiesPartial.cshtml
@model SportCommunityRM.WebSite.ViewModels.Shared.ActivitiesViewModel

<div id="activities-container">
    @Html.DisplayFor(model => model.Activities)
</div>

<script type="text/javascript">
    $(function () {
        var pagingListAnchorHandler = function (event) {
            event.preventDefault();
            var hrefValue = $(this).attr('href').substring(1);
            var url = '@Url.Action(nameof(IActivityController.GetActivitiesAsync))' + hrefValue;
            var successCallback = function (response) {
                $('#activities-container').html(response);
            };
            var errorCallback = function (response) {
                bootbox.alert('Error!');
            };
            executeHttpGetRequest(url, null, successCallback, errorCallback);
        };

        $(document).on('click', '#activities-container table thead th a', pagingListAnchorHandler);
        $(document).on('click', '#activities-container nav .pagination li a', pagingListAnchorHandler);
    });
</script>

src/SportCommunityRM.WebSite/Views/Shared/_BakLayout.cshtml
@{ 
    var twoLetterIsoLanguage = System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName.ToLower(); 
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @WebSiteResources.WebSiteName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/fullcalendar/dist/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/lib/cropbox/jquery.cropbox.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/scrm.css" />
        <link rel="stylesheet" href="~/css/accent.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/scrm.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/javascript-detect-element-resize/jquery.resize.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).js"></script>
        <script src="~/lib/bootstrap3-typeahead/bootstrap3-typeahead.min.js"></script>
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
        <script src="~/lib/underscore/underscore-min.js"></script>
        <script src="~/lib/fullcalendar/dist/fullcalendar.min.js"></script>
        <script src="~/lib/fullcalendar/dist/locale-all.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"
                asp-fallback-src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).min.js"
                asp-fallback-src="~/lib/bootstrap-datepicker/js/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

</head>
<body style="background: linear-gradient(to bottom, transparent, #0081cc 70%), url('/images/team_test.jpg') center no-repeat, #0081cc;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SportCommunityRM.WebSite</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_TopNavbarPartial")
                @await Component.InvokeAsync("Login")
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        @Html.Partial("_FooterPartial")
    </div>

    <script type="text/javascript">
        $(function () {
            moment.locale('@twoLetterIsoLanguage');
            var datePickerOptions = defaultDatepickerOptions;
            datePickerOptions.language = '@twoLetterIsoLanguage';
            $('.datepicker').datepicker(datePickerOptions);
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SportCommunityRM.WebSite/Views/Shared/_FooterPartial.cshtml
<hr />
<footer class="parallax-footer">
    <p>&copy; @DateTime.Now.Year - @WebSiteResources.WebSiteName</p>
</footer>

src/SportCommunityRM.WebSite/Views/Shared/_Layout.cshtml
@{ 
    var twoLetterIsoLanguage = System.Threading.Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName.ToLower();
}
<!DOCTYPE html>
<html class="parallax-html">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @WebSiteResources.WebSiteName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/lib/fullcalendar/dist/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/lib/cropbox/jquery.cropbox.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/scrm.css" />
        <link rel="stylesheet" href="~/css/accent.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/scrm.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/javascript-detect-element-resize/jquery.resize.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).js"></script>
        <script src="~/lib/bootstrap3-typeahead/bootstrap3-typeahead.min.js"></script>
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/bootbox.js/bootbox.js"></script>
        <script src="~/lib/underscore/underscore-min.js"></script>
        <script src="~/lib/fullcalendar/dist/fullcalendar.min.js"></script>
        <script src="~/lib/fullcalendar/dist/locale-all.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"
                asp-fallback-src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).min.js"
                asp-fallback-src="~/lib/bootstrap-datepicker/js/locales/bootstrap-datepicker.@(twoLetterIsoLanguage).js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="margin-bottom: 0">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SportCommunityRM.WebSite</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_TopNavbarPartial")
                @await Component.InvokeAsync("Login")
            </div>
        </div>
    </nav>

    @RenderSection("ParallaxBgStyleSection")

    <header class="parallax-header">
        <div class="parallax-container row">
            @RenderSection("HeaderSection")
        </div>
    </header>

    <main class="parallax-container row">
        @RenderBody()
        <div class="col-md-12">
            @Html.Partial("_FooterPartial")
        </div>
    </main>

    <script type="text/javascript">
        $(function () {
            moment.locale('@twoLetterIsoLanguage');
            var datePickerOptions = defaultDatepickerOptions;
            datePickerOptions.language = '@twoLetterIsoLanguage';
            $('.datepicker').datepicker(datePickerOptions);
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/SportCommunityRM.WebSite/Views/Shared/_NewsFeedPartial.cshtml
@model SportCommunityRM.WebSite.ViewModels.Shared.NewsFeedViewModel

<div id="news-feed-container">
    @Html.DisplayFor(model => model.NewsFeed)
</div>

<script type="text/javascript">
    $(function () {
        var pagingListAnchorHandler = function (event) {
            event.preventDefault();
            var hrefValue = $(this).attr('href').substring(1);
            var url = '@Url.Action(nameof(INewsFeedController.GetFeedAsync))' + hrefValue;
            var successCallback = function (response) {
                $('#news-feed-container').html(response);
            };
            var errorCallback = function (response) {
                bootbox.alert('Error!');
            };
            executeHttpGetRequest(url, null, successCallback, errorCallback);
        };

        $(document).on('click', '#news-feed-container nav .pagination li a', pagingListAnchorHandler);
    });
</script>

src/SportCommunityRM.WebSite/Views/Shared/_TopNavbarPartial.cshtml
<ul class="nav navbar-nav">
    <li>
        <a asp-action="Index" asp-controller="Home">
            Home <i class="fa fa-home"></i>
        </a>
    </li>
    <li>
        <a asp-action="Index" asp-controller="Coach">
            Coaches <i class="fa fa-user"></i>
        </a>
    </li>
    <li>
        <a asp-action="Index" asp-controller="Team">
            Teams <i class="fa fa-group"></i>
        </a>
    </li>
</ul>